[package]
authors = ["Walther Chen <walther.chen@gmail.com>"]
name = "mondrian-rest-cli"
version = "0.1.0"

[dependencies]
failure = "0.1.1"
reqwest = "0.8.2"
structopt = "0.1.6"
structopt-derive = "0.1.6"
